
FROM node:20-slim AS builder
ENV VITE_API_URL=http://localhost:8000
WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:20-slim

WORKDIR /app

COPY --from=builder /app/dist ./dist

RUN npm install -g serve

EXPOSE 5173

CMD ["npx", "serve", "-s", "dist", "-l", "5173"]
